# Generated by Django 3.0.5 on 2020-07-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='posteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_exos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correction',
            name='correcteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_correcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correction',
            name='enonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcs', to='filemanager.Exercice'),
        ),
    ]
