# Generated by Django 3.0.5 on 2020-06-30 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0002_auto_20200616_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='correcteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_correcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correction',
            name='enonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcs', to='filemanager.Exercice'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='posteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_exos', to=settings.AUTH_USER_MODEL),
        ),
    ]
