# Generated by Django 3.0.5 on 2020-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_auto_20200421_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
