# Generated by Django 3.0.5 on 2020-08-02 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0003_auto_20200802_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='mean_rating',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='rated_by',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('correc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='filemanager.Correction')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
