# Generated by Django 3.0.5 on 2020-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_auto_20200630_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='nom_etablissement',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='exercice',
            name='nom_prof',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='exercice',
            name='prefix_prof',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='ville_etablissement',
            field=models.CharField(default='Admin', max_length=40),
        ),
    ]
