# Generated by Django 2.2.7 on 2020-08-10 11:26

from django.db import migrations, models
import exos_app.settings.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_auto_20200809_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=exos_app.settings.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
