# Generated by Django 2.2.7 on 2020-08-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0008_correction_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
