# Generated by Django 2.2.7 on 2020-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0009_exercice_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='voie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
