# Generated by Django 3.0.5 on 2020-06-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sexe_prof',
            new_name='prefix_prof',
        ),
    ]
