# Generated by Django 3.0.5 on 2020-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
