# Generated by Django 3.0.5 on 2020-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_correction_price'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bought_correc',
            field=models.ManyToManyField(related_name='buyers', to='filemanager.Correction'),
        ),
    ]
