# Generated by Django 3.0.5 on 2020-08-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='classe',
            new_name='niveau',
        ),
    ]
