# Generated by Django 3.0.5 on 2020-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200620_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='etablissement',
            new_name='nom_etablissement',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville_etablissement',
            field=models.CharField(default='Admin', max_length=40),
        ),
    ]
