# Generated by Django 3.0.5 on 2020-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_auto_20200616_1939'),
        ('users', '0003_auto_20200620_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='correc',
            new_name='unlocked_correcs',
        ),
        migrations.AddField(
            model_name='customuser',
            name='exo_favoris',
            field=models.ManyToManyField(related_name='liked_by', to='filemanager.Exercice'),
        ),
    ]
