# Generated by Django 2.2.7 on 2020-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
