# Generated by Django 3.0.5 on 2020-06-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200629_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='exo_favoris',
            new_name='liked_exos',
        ),
    ]
